### ISSUE TITLE
No se puede poner el evento modalSubmit en un event handler

### ISSUE THREAD

**Issue by PabloRNC** [Mateo-tem/discord-modals#1]
No se si esto es un error como tal pero he probado muchas veces y no se puede meter el evento modalSubmit en el event handler con lo cual solo se puede meter en el index. Sería un buen punto para esta npm que se pudiese meter ahí ya que ayuda mucho más a la organización de todos los códigos

**Comment by Mateo-tem** [comment]
No sé que tipo de Event Handler tendrás, pero a mí si me funciona. Prueba con este handler a ver si te funciona.
**De todos modos, gracias por reportar el error.**

![ModalSubmit](https://user-images.githubusercontent.com/79017590/154158628-790876d0-b51b-4c2f-8eda-205aa7317668.png)
![Event Handler](https://user-images.githubusercontent.com/79017590/154158725-c0fa1f64-e47a-4a06-b202-87865b1d7360.jpg)

.

**Comment by PabloRNC** [comment]
Vale lo que me faltaba era poner client, gracias por tu ayuda
