### ISSUE TITLE
Slash Command Not Registering

### ISSUE THREAD

**Issue by Code19Master** [Mateo-tem/discord-modals#10]
I did the same step in README.MD but my slash command isn't showing up

**Comment by Mateo-tem** [comment]
I think that is not a package issue, you can kick your bot of the server and then add it again.

**Comment by Code19Master** [comment]
Okay.. I figured it out afterwards that it was discord.js problem Thanx for the great Work on this package.

**Comment by Mateo-tem** [comment]
No problem. 😄
