### ISSUE TITLE
Error: Cannot find module './src/v14/Interaction'

### ISSUE THREAD

**Issue by MaximeBeasse** [Mateo-tem/discord-modals#109]
Hi,

It seems that the 1.3.8 version is missing the `./src/v14/Interaction.js` file, or there is a mistake in the exports.

Thanks in advance!

**Comment by Mateo-tem** [comment]
Oh yes, there is a mistake in the exports. I've deleted the file because v14 already has the BaseInteraction class, so it will be useless. I will upload version 1.3.9!
