### ISSUE TITLE
Modals do not have author property

### ISSUE THREAD

**Issue by zhidaodev** [Mateo-tem/discord-modals#11]
Requesting a more informational class for <Modal>

not sure how I would code this, but someone will have to do it someday, for this package or for discord.js

**Comment by PabloRNC** [comment]
Is modal.user

**Comment by Mateo-tem** [comment]
Oh, the modal parameter of the modalSubmit event is the ModalSubmitInteraction class, this have the `.user` property, so you can access to the author of the Modal Submit Interaction.

**Comment by zhidaodev** [comment]
oh i didn't know

i'd add it to the docs

thanks!
