### ISSUE TITLE
modalSubmit event doesn't work

### ISSUE THREAD

**Issue by Sedorikku1949** [Mateo-tem/discord-modals#12]
Hello, i have a problem with the Modal Event...

When i submit some modal like that :

![image](https://user-images.githubusercontent.com/73949405/155854825-72172650-23e0-4ecf-a0a8-2b05ef04af38.png)

but in my event manager, i have this code : 
```js
const { Client, Intents } = require("discord.js")
const { readdirSync } = require("fs");
const discordModals = require('discord-modals')

global["client"] = new Client({
  intents: 32767,
  partials: ["CHANNEL"],
  fetchAllMembers: true,
  allowedMentions: { repliedUser: false },
  retryLimit: 5,
  invalidRequestWarningInterval: 10
});
discordModals(client);
client.prefix = ".";

client.on('modalSubmit', (modal) => {
  if(modal.customId === 'modal-customid'){
    const firstResponse = modal.getTextInputValue('textinput-customid')
    modal.reply('Congrats! Powered by discord-modals.' + `\`\`\`${firstResponse}\`\`\``)
  }  
})
```

Can someone know why the event didn't response ?

**Comment by PabloRNC** [comment]
It can be that you put wrong the modal id

**Comment by Mateo-tem** [comment]
Show me your other code, where you show the Modal.

**Comment by Sedorikku1949** [comment]
This is the code in my command : ```js
const { Message } = require('discord.js');
const { Modal, TextInputComponent, showModal } = require('discord-modals') // Now we extract the showModal method
const modal = new Modal() // We create a Modal
  .setCustomId('modal-customid')
  .setTitle('Test of Discord-Modals!')
  .addComponents(
    new TextInputComponent() // We create a Text Input Component
    .setCustomId('textinput-customid')
    .setLabel('Some text Here')
    .setStyle('SHORT') //IMPORTANT: Text Input Component Style can be 'SHORT' or 'LONG'
    .setMinLength(4)
    .setMaxLength(10)
    .setPlaceholder('Write a text here')
    .setRequired(true) // If it's required or not
  );


module.exports.exec = async function(author, channel, guild, memberPermission, member, interaction, options){
  if (interaction instanceof Message) {
    // message, need options[0]
  } else {
    // slashCommand, send modal

    showModal(modal, {
      client: client,
      interaction: interaction
    })
  }
}

module.exports.config = {
  name: "suggestion",
  aliase: ["suggest"],
  category: "util",
  defer: false,
  options: [],
  system: {
    requiredPermission: ["SEND_MESSAGES", "EMBED_LINKS"],
    userPermission: [],
    staff: false,
    dev: false,
    inProgress: false,
    isUserCommand: false,
    isSlashCommand: true
  },
  lang: null,
  path: null
}
```

**Comment by Mateo-tem** [comment]
Do you have your modalSubmit event on your main file? And in the console, there is not an error?

**Comment by Sedorikku1949** [comment]
I don't have any message in the console ans yes this is in the main file, all others events works properly

**Comment by Mateo-tem** [comment]
And if you put your modalSubmit event in an Event Handler?

**Comment by Sedorikku1949** [comment]
I have try at the begin, but when i saw that this don't work properly, i have change to a classic client.on in the main file

**Comment by Mateo-tem** [comment]
Can you show me your code of your Event Handler?

**Comment by Sedorikku1949** [comment]
This is my Event Handler :
```js
const { Client, Intents } = require("discord.js");
const { readdirSync } = require("fs");
const discordModals = require('discord-modals');

global["client"] = new Client({
  intents: Object.keys(Intents.FLAGS),
  partials: ["CHANNEL"],
  fetchAllMembers: true,
  allowedMentions: { repliedUser: false },
  retryLimit: 5,
  invalidRequestWarningInterval: 10
});
discordModals(client);
client.prefix = ".";

// EVENTS
// all files in "_listeners" are a function that is exported
readdirSync("_listeners").forEach((dir) => {
  try { client.on(dir.replace(/\.js/g, ""), require(`./_listeners/${dir}`)) }
    catch(err) { console.log(err) }
})

global["database"] = new (require("./_managers/Database.js"))()

// MANAGERS && PROTOTYPE
require("./_managers/Prototype.js").exec()
new (require("./_managers/_commands/CommandsManager.js"))()
new (require("./_managers/_interactions/InteractionManager.js"))()

// LOGIN
client.login(require("./_storage/config.json").token)

module.exports = client;
```

**Comment by Mateo-tem** [comment]
What if you put `console.log(modal)` at the beginning of the modalSubmit event?

**Comment by Sedorikku1949** [comment]
When i put a console.log at thé beginning, nothing is sending to the console

**Comment by Mateo-tem** [comment]
Hmmm, you can share a GitHub repository with your code? It would be easier to help you, probably this is not a package error.

**Comment by Sedorikku1949** [comment]
I have uploaded the package at https://github.com/Sedorikku1949/LanaNextGeneration

**Comment by Mateo-tem** [comment]
What is your main file?

**Comment by Sedorikku1949** [comment]
The app.js is the start of the bot, and in _managers, you have CommandManager for commands and InteractionManager for interactions like buttons and select menu ( this manager is called in the event InteractionCreate )

**Comment by Mateo-tem** [comment]
If all works, probably `discordModals(client)` is placed in a part of the code where it should not be, so it does not emit the modalSubmit event.

**Comment by Sedorikku1949** [comment]
After some manipulations, i have found the problem : 
in the ready event, we need to put : 
```js
client.on('modalSubmit', async(modal) => {
    console.log(modal)
    if(modal.customId === 'modal-customid'){
      const firstResponse = modal.getTextInputValue('textinput-customid')
      await modal.deferReply({ ephemeral: true })
      modal.followUp({ content: 'Congrats! Powered by discord-modals.' + `\`\`\`${firstResponse}\`\`\``, ephemeral: true })
    }  
  })
  client.ws.on('INTERACTION_CREATE', (data) => {
    if (!data.type) return;    
    if (data.type == 5) {
      client.emit('modalSubmit', new (require('discord-modals').ModalSubmitInteraction)(client, data));
    } else return;
  });
  ```
  ⚠️ That doesn't work with the classic method, and the event is not added before the bot is logged in :wink:

**Comment by Sedorikku1949** [comment]
Oh and the event is emit twice :')

**Comment by Mateo-tem** [comment]
Uhmmm and if you detete this?

```javascript
client.ws.on('INTERACTION_CREATE', (data) => {
    if (!data.type) return;    
    if (data.type == 5) {
      client.emit('modalSubmit', new (require('discord-modals').ModalSubmitInteraction)(client, data));
    } else return;
  });
```

**Comment by Sedorikku1949** [comment]
No event is emiting :(

**Comment by Mateo-tem** [comment]
And if you delete this?

```javascript
client.on('modalSubmit', async(modal) => {
    console.log(modal)
    if(modal.customId === 'modal-customid'){
      const firstResponse = modal.getTextInputValue('textinput-customid')
      await modal.deferReply({ ephemeral: true })
      modal.followUp({ content: 'Congrats! Powered by discord-modals.' + `\`\`\`${firstResponse}\`\`\``, ephemeral: true })
    }  
  })
```

**Comment by Sedorikku1949** [comment]
The modal interaction is received

**Comment by Mateo-tem** [comment]
Ok, so it's solved?

**Comment by Sedorikku1949** [comment]
yes 👍

**Comment by Mateo-tem** [comment]
Ok, so can I close the issue?

**Comment by Sedorikku1949** [comment]
Yes of course

**Comment by myungjunChae** [comment]
> 

This works for me. Thanks!
