### ISSUE TITLE
v14 support ?

### ISSUE THREAD

**Issue by ARR4NN** [Mateo-tem/discord-modals#16]
Doesnt work in v14
I know modals are meant for v14 to implement but they are being slow. Could you try to make this work on v14 discord.js@dev

**Comment by Mateo-tem** [comment]
Yeah, that will be in development. Probably in the next version will be ready.

**Comment by ARR4NN** [comment]
K thanks

**Comment by Mateo-tem** [comment]
Now, discord-modals support discord.js v14!
