### ISSUE TITLE
modal.guild undefined

### ISSUE THREAD

**Issue by PabloRNC** [Mateo-tem/discord-modals#2]
Al intentar hacer un comando de banear a través de la id da undefined modal.guild.

**Comment by Mateo-tem** [comment]
**¡Gracias por reportar el error!**

Se ha solucionado este error en la versión 1.1.2 gracias a tu reporte. ¡Saludos!
Ahora la propiedad `.guild` devuelve un objeto Guild correctamente, al igual que `.channel`, entre otros.
