### ISSUE TITLE
Añadir evento cuando el modal se cancela

### ISSUE THREAD

**Issue by PabloRNC** [Mateo-tem/discord-modals#22]
No sé si esto se podría añadir o si por otro lado no sé puede y tendríamos que esperar a que actualicen esto en la API pero si no es así podrías añadir un evento para cuando el modal se cancele llamado tipo modalCancel o algo por el estilo

**Comment by Mateo-tem** [comment]
**¡Gracias por la sugerencia!**

No se podría añadir eso. Todo es según la API de Discord, que no tiene dicho evento. El evento `modalSubmit` es parte de una interacción de Discord API del tipo `MODAL_SUBMIT`, pero modalCancel no tiene un evento/tipo para que sea emitido.

**Comment by PabloRNC** [comment]
Ok
