### ISSUE TITLE
setPlaceholder type definition missing

### ISSUE THREAD

**Issue by Hardcodex1** [Mateo-tem/discord-modals#29]
Type definition for setPlaceholder is missing from class modal. While using typescript throws error
![image](https://user-images.githubusercontent.com/83858691/158008206-0e195294-293f-4486-8c38-c594dcc91529.png)
![image](https://user-images.githubusercontent.com/83858691/158008222-9d0444de-c56c-43ed-a335-19b85579057e.png)
FIX (Add type in definition)
![image](https://user-images.githubusercontent.com/83858691/158008248-ab23e31f-2b2f-44a6-b96e-20a6f0ba4006.png)

**Comment by Mateo-tem** [comment]
Type definitions for `Modal` or `TextInputComponent`?

**Comment by Mateo-tem** [comment]
Well, I think is a mistake, no problem. 
**Thanks to report the issue!**
I forgot to add that type. It will be fixed in the next version, that will be published today.

**Comment by Mateo-tem** [comment]
Fixed.
