### ISSUE TITLE
Message cloning

### ISSUE THREAD

**Issue by xMufaro** [Mateo-tem/discord-modals#3]
I made a modal that after submitting, puts input text value into embedded message in specific channel. First submit is good, but when another comes out, it puts the old embed and the new embed (2 embeds) and every submit it just goes up by 1 one

**Comment by Mateo-tem** [comment]
Can you explain in more detail, please?
From what I understand, you say that embedded messages are duplicated after a second modal is submitted. is that correct?

**Comment by xMufaro** [comment]
First submit sends only one message, second submit sends two messages etc. Maybe it's my fault but I don't know.

**Comment by Mateo-tem** [comment]
Can you show me your code, please?

**Comment by Mateo-tem** [comment]
Ok, I think it's solved. If it's not solved, please open the issue again.
