### ISSUE TITLE
Support for json

### ISSUE THREAD

**Issue by benzon** [Mateo-tem/discord-modals#32]
Hey i know you created this like embeds with the way you build the modal.

But could support for json be added? so we can post a json array with all the options, think that would make it easyer to create dynamic forms.

So ex

```
const exampleModal = {
			type: 9,
			data: {
				title: 'LosKros Register',
				custom_id: 'register',
				components: [
					{
						type: 1,
						components: [
							{
								type: 4,
								custom_id: 'register',
								label: 'Some random label',
								style: 1,
								min_length: 2,
								max_length: 400,
								required : true,
							},
						],
					},
				],
			},
		},
```
showModalJSON(exampleModal , {
      client: client,
      interaction: interaction
 })
 
 Just an example the last part might be a better way to do it.
 
 But would make life a lot easyer, creating modals, just using the json format as well.

**Comment by Mateo-tem** [comment]
Do you prefer to show the modal like this, or like you said?

```js
title: 'LosKros Register',
custom_id: 'register',
components: [
	{
		type: 1,
		components: [
			{
				type: 4,
				custom_id: 'register',
				label: 'Some random label',
				style: 1,
				min_length: 2,
				max_length: 400,
				required : true,
			},
		],
	},
],
```

**Comment by benzon** [comment]
Gotta say your method is cleaner so would go for that with out doubt.

That way it's possible to do create modals dynamicly and save the layout to db and what not :)

**Comment by Mateo-tem** [comment]
No problem! I will add it in the next version that probably will be published today :)

**Comment by benzon** [comment]
Sounds great! Will be looking forward to it with out doubt.

**Comment by Mateo-tem** [comment]
:D

**Comment by Mateo-tem** [comment]
**Done!**
