### ISSUE TITLE
Error [INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.

### ISSUE THREAD

**Issue by kabirsingh2004** [Mateo-tem/discord-modals#33]
bro i am facing a error

>>> when i run cmd and then i run modal based it given error `Error [INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.` 

but if i not defer interaction then others cmds not work and when i not defer then modals based cmds not work

**Comment by Mateo-tem** [comment]
Can you send me your code, please?

**Comment by ExZy3** [comment]
> i fixed thanks

how can u help me?

**Comment by aldo026** [comment]
![image](https://user-images.githubusercontent.com/92898488/172056349-2ac7947c-abc6-4afd-9905-de358cdbe5b5.png)
pls help

**Comment by aldo026** [comment]
![image](https://user-images.githubusercontent.com/92898488/172056416-d959ae0c-34a4-403f-82b7-fc8510ca9166.png)
