### ISSUE TITLE
Typescript compile error

### ISSUE THREAD

**Issue by ShortByte** [Mateo-tem/discord-modals#37]
Hey, I wanted to add modals to my Discord bot. My bot is written in Typescript and I get the following error when compiling.

Application still works fine though.

```
node_modules/discord-modals/index.d.ts:119:3 - error TS2416: 
Property 'type' in type 'ModalSubmitField'  is not assignable to the same property in base type 'BaseMessageComponent'.
  Type 'string' is not assignable to type '"ACTION_ROW" | "BUTTON" | "SELECT_MENU"'.

119   type: string;
```

**Comment by Mateo-tem** [comment]
**Thanks to report the issue!**

Will be fixed in the next version, which will be published today.
