### ISSUE TITLE
I got error 

### ISSUE THREAD

**Issue by CatingEzz** [Mateo-tem/discord-modals#43]
Error ```bash
SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Interaction has already been acknowledged.  
    at RequestHandler.execute (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async showModal (C:\Users\david\desktop\Cating\node_modules\discord-modals\src\structures\ShowModal.js:31:9) {
  method: 'post',
  path: '/interactions/955051216927346748/aW50ZXJhY3Rpb246OTU1MDUxMjE2OTI3MzQ2NzQ4OmJuQU9mdlRscHMzRFpsN0VaS1NSM0lheUJObU5XN3pzeXVXZGtaRTkxUUZVVWdPcHF4TDlKMXVkSm8zakIyNGJjZ1ptSVZ3V3M5azVNMTRTZGlGVEI5N1FTZHl0SlN2MWd2VDFEN1hpQWtZajRYNWxDbk5WTlRPUFFVV1JBSFhT/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 9, data: [Object] }, files: [] }
}```
and Code https://cdn.discordapp.com/attachments/900008888441667596/955058633417322577/unknown.png

**Comment by Reubzz** [comment]
This happens because you might have `interaction.deferReply()` in your `interactionCreate.js` file if you have a command handler in place. 

If you don't have a command handler. Kindly send additional Info such as your `Index.js` file and the command file. Upload the Files in anywhere pastebin or whatever will do.

**Comment by CatingEzz** [comment]
Hm, i don't have `interaction.deferReply()` from in `interactionCreate.js` I'll send you https://cdn.discordapp.com/attachments/939207412320174160/955091028740804668/unknown.png That's from `interactionCreate.js` also `index.js` -> https://cdn.discordapp.com/attachments/939207412320174160/955091198979235860/unknown.png

**Comment by ghazera** [comment]
I have a similar error, ReferenceError: showModal is not defined

and I don't understand where it comes from, knowing that I am importing the modules into the script as shown

**Comment by Mateo-tem** [comment]
> I have a similar error, ReferenceError: showModal is not defined
> 
> and I don't understand where it comes from, knowing that I am importing the modules into the script as shown

Can you show me your code, please?

**Comment by Mateo-tem** [comment]
> Error `bash SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Interaction has already been acknowledged. at RequestHandler.execute (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:350:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RequestHandler.push (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:51:14) at async showModal (C:\Users\david\desktop\Cating\node_modules\discord-modals\src\structures\ShowModal.js:31:9) { method: 'post', path: '/interactions/955051216927346748/aW50ZXJhY3Rpb246OTU1MDUxMjE2OTI3MzQ2NzQ4OmJuQU9mdlRscHMzRFpsN0VaS1NSM0lheUJObU5XN3pzeXVXZGtaRTkxUUZVVWdPcHF4TDlKMXVkSm8zakIyNGJjZ1ptSVZ3V3M5azVNMTRTZGlGVEI5N1FTZHl0SlN2MWd2VDFEN1hpQWtZajRYNWxDbk5WTlRPUFFVV1JBSFhT/callback', code: 40060, httpStatus: 400, requestData: { json: { type: 9, data: [Object] }, files: [] } }` and Code https://cdn.discordapp.com/attachments/900008888441667596/955058633417322577/unknown.png

And if you execute the Command, it tells you like "Bot is thinking..."? Or the bot reply something?

**Comment by CatingEzz** [comment]
> > Error `bash SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Interaction has already been acknowledged. at RequestHandler.execute (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:350:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RequestHandler.push (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:51:14) at async showModal (C:\Users\david\desktop\Cating\node_modules\discord-modals\src\structures\ShowModal.js:31:9) { method: 'post', path: '/interactions/955051216927346748/aW50ZXJhY3Rpb246OTU1MDUxMjE2OTI3MzQ2NzQ4OmJuQU9mdlRscHMzRFpsN0VaS1NSM0lheUJObU5XN3pzeXVXZGtaRTkxUUZVVWdPcHF4TDlKMXVkSm8zakIyNGJjZ1ptSVZ3V3M5azVNMTRTZGlGVEI5N1FTZHl0SlN2MWd2VDFEN1hpQWtZajRYNWxDbk5WTlRPUFFVV1JBSFhT/callback', code: 40060, httpStatus: 400, requestData: { json: { type: 9, data: [Object] }, files: [] } }` and Code https://cdn.discordapp.com/attachments/900008888441667596/955058633417322577/unknown.png
> 
> And if you execute the Command, it tells you like "Bot is thinking..."? Or the bot replies something?

Bot say: https://discord.ggez.fun/cating/sfs3V7ad

**Comment by Mateo-tem** [comment]
> > > Error `bash SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Interaction has already been acknowledged. at RequestHandler.execute (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:350:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RequestHandler.push (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:51:14) at async showModal (C:\Users\david\desktop\Cating\node_modules\discord-modals\src\structures\ShowModal.js:31:9) { method: 'post', path: '/interactions/955051216927346748/aW50ZXJhY3Rpb246OTU1MDUxMjE2OTI3MzQ2NzQ4OmJuQU9mdlRscHMzRFpsN0VaS1NSM0lheUJObU5XN3pzeXVXZGtaRTkxUUZVVWdPcHF4TDlKMXVkSm8zakIyNGJjZ1ptSVZ3V3M5azVNMTRTZGlGVEI5N1FTZHl0SlN2MWd2VDFEN1hpQWtZajRYNWxDbk5WTlRPUFFVV1JBSFhT/callback', code: 40060, httpStatus: 400, requestData: { json: { type: 9, data: [Object] }, files: [] } }` and Code https://cdn.discordapp.com/attachments/900008888441667596/955058633417322577/unknown.png
> > 
> > 
> > And if you execute the Command, it tells you like "Bot is thinking..."? Or the bot replies something?
> 
> Bot say: https://discord.ggez.fun/cating/sfs3V7ad

I don't know where but you have `interaction.deferReply()`.

**Comment by Mateo-tem** [comment]
it's solved?

**Comment by Turtlepaw** [comment]
I have gotten this error several times. My problem is that I was using the `showModal()` function on an interaction that I already replied to.

**Comment by Turtlepaw** [comment]
> I have a similar error, ReferenceError: showModal is not defined
> 
> and I don't understand where it comes from, knowing that I am importing the modules into the script as shown

You probably haven't imported Discord Modals yet! You can do that like this:

```js
//js
const { showModal } = require("discord-modals");
//ts
import { showModal } from "discord-modals";
```

**Comment by uSebazz** [comment]
> Error `bash SHOW_MODAL_ERROR: An error occurred when showing a modal. DiscordAPIError: Interaction has already been acknowledged. at RequestHandler.execute (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:350:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async RequestHandler.push (C:\Users\david\desktop\Cating\node_modules\discord.js\src\rest\RequestHandler.js:51:14) at async showModal (C:\Users\david\desktop\Cating\node_modules\discord-modals\src\structures\ShowModal.js:31:9) { method: 'post', path: '/interactions/955051216927346748/aW50ZXJhY3Rpb246OTU1MDUxMjE2OTI3MzQ2NzQ4OmJuQU9mdlRscHMzRFpsN0VaS1NSM0lheUJObU5XN3pzeXVXZGtaRTkxUUZVVWdPcHF4TDlKMXVkSm8zakIyNGJjZ1ptSVZ3V3M5azVNMTRTZGlGVEI5N1FTZHl0SlN2MWd2VDFEN1hpQWtZajRYNWxDbk5WTlRPUFFVV1JBSFhT/callback', code: 40060, httpStatus: 400, requestData: { json: { type: 9, data: [Object] }, files: [] } }` and Code https://cdn.discordapp.com/attachments/900008888441667596/955058633417322577/unknown.png

I think you have `interaction.deferReply()` ?
