### ISSUE TITLE
injected prefill value into textfield

### ISSUE THREAD

**Issue by NoahMo** [Mateo-tem/discord-modals#5]
before i start the discussion, i would like to show my gratitude - thank you Mateo-tem.

i was struggling to inject custom values into the modal text fields when it opens up and i found out the final method of TextInputComponent .js module - toJSON() has value missing out. after adding "value: this.value" into the object, the builder starts accepting variables and prefills the form.

not sure if it is by design or just missing out.

**Comment by Mateo-tem** [comment]
**¡Thanks to report the issue! Yes, you are right, the `.toJSON()` method, has value missing out. I apologize for the error.**

Yeah, the value prefills the form, and if it stays that way, the `.value` property of the TextInputComponent will give you the prefilled value. This will be corrected in version 1.1.6.
