### ISSUE TITLE
Modals for messageCreate event

### ISSUE THREAD

**Issue by Luncaaa** [Mateo-tem/discord-modals#50]
Hello o/
Is it possible to open a modal on a command with messageCreate event (for example: !help)? If it's possible, how can I do it? And if it isn't possible, do you think it will be added?

By the way, great package!

**Comment by Mateo-tem** [comment]
**Hello, thanks to open the issue!**
Yes and no, because modals **are only for interactions**. Yes, because you can create a button/select menu on a message (they are interactions) and if you click it, you can show the modal but without them, it's not possible.

**Comment by Luncaaa** [comment]
I see, thank you!
Have a nice day :)
