### ISSUE TITLE
modalSubmit interaction member sometimes returns null

### ISSUE THREAD

**Issue by jebe22** [Mateo-tem/discord-modals#51]
> TypeError: Cannot read properties of null (reading 'user') -> at C:\Users\dddd\Desktop\ddd\index.ts:54:55

Line 54 is highlighted, only tries to print the member.user, returning null
![image](https://user-images.githubusercontent.com/81528820/160179083-128753ff-ea10-44b0-b608-4efd577ca1ae.png)

Is there any fix to this? I need the member to not to be null on some modal submits, as it creates an embed after it with the user info.

**Comment by Mateo-tem** [comment]
**Thanks to report this issue!**
I don't have an explanation for this, but you can access the user using the `#user` property. Like `modal.user`.
I will try to check the problem with the `#member` property and try to solve it.
