### ISSUE TITLE
Error when using modal

### ISSUE THREAD

**Issue by Luncaaa** [Mateo-tem/discord-modals#52]
Hello!
 
I've been testing some commands using modals and every time I use the same command twice (and therefore the same modal opens) I get an error.

For example, if I run /modal and fill the modal, everything goes great but if after that I run /modal again and I fill the modal with the same text, the bot will crash with the error 'Interaction has already been acknowledged.'

Code: https://pastebin.com/APQftuwn
Error: [https://pastebin.com/sc8FKJU1](https://pastebin.com/sc8FKJU1)

**Comment by Mateo-tem** [comment]
but it works?

**Comment by Luncaaa** [comment]
What do you mean?

When I first run the command, the **modal.reply(`${dia} ... ${accion} ... ${cosas}`);** message is sent correctly. If I run it a second time, the message is also sent but the bot turns off with the error I sent and I need to turn it on again

**Comment by Mateo-tem** [comment]
in the second time, it gives you an error that says 'La aplicación no ha respondido' or 'The application did not respond'?

**Comment by Luncaaa** [comment]
Nope, the message is sent but the error **DiscordAPIError: Interaction has already been acknowledged.** appears on console

**Comment by Mateo-tem** [comment]
Nono, I mean on the Discord Application.

**Comment by Luncaaa** [comment]
Yeah, I understood, there are no errors there

**Comment by Mateo-tem** [comment]
Sure? Or appears an error in the modal, like 'Algo ha salido mal' or 'Something went wrong'?

**Comment by Luncaaa** [comment]
Yeah. In the video it does not appear but when I ran the 1st command, I opened the command promt to show that there were no errors and when I ran the command for the 2nd time, I opened it again to show that the error was there. 
VIDEO: [https://drive.google.com/file/d/1pKgRWplLK_XeWZAyChpEX4Vd30fv553n/view?usp=sharing](https://drive.google.com/file/d/1pKgRWplLK_XeWZAyChpEX4Vd30fv553n/view?usp=sharing)

**Comment by jebe22** [comment]
You should remove your **client.on modalSubmit** from the slash command and put it somewhere else (index.js for example), this should most likely fix your problem

**Comment by Luncaaa** [comment]
That fixed it!
Thank you so much :)

**Comment by Mateo-tem** [comment]
Good!
