### ISSUE TITLE
Getting Users ID

### ISSUE THREAD

**Issue by dubfib** [Mateo-tem/discord-modals#54]
How can I get the users ID with the modal property?

**Comment by Mateo-tem** [comment]
what do you mean?

**Comment by dubfib** [comment]
> what do you mean?

I want to get the users id after they submit a modal.

**Comment by dubfib** [comment]
also ur very quick lol

**Comment by Mateo-tem** [comment]
`modal.user.id`

**Comment by dubfib** [comment]
thank you

**Comment by Mateo-tem** [comment]
np
