### ISSUE TITLE
Disabled input?

### ISSUE THREAD

**Issue by nabtron** [Mateo-tem/discord-modals#57]
Can we disable an input box on modal?

**Comment by Mateo-tem** [comment]
Nope, that is not possible, because the input box is supposed to be filled.

**Comment by nabtron** [comment]
@Mateo-tem can we add description / text above the input box (except label), to explain etc.?

**Comment by Mateo-tem** [comment]
Uhmm, No, that's not possible because Discord API didn't add that.
