### ISSUE TITLE
[INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.

### ISSUE THREAD

**Issue by Ivancito-N** [Mateo-tem/discord-modals#59]
Tengo este error,
![image](https://user-images.githubusercontent.com/99850366/161388800-031fe25b-df06-435f-9ce0-7f037408e7dc.png)
En la línea 5 y 6 hice un apaño, pero me gustaría ponerlo para que funcionara, pero el bot se queda pensando --> 
![2022-04-02 (3)](https://user-images.githubusercontent.com/99850366/161388637-6b4a456f-dfa9-42f7-a0b4-ad37677337a1.png)

**Comment by Mateo-tem** [comment]
¿Y que tendría que ver esto con discord-modals?
