### ISSUE TITLE
No poner repuesta al modal 

### ISSUE THREAD

**Issue by PabloRNC** [Mateo-tem/discord-modals#6]
Si no pones nada que responda el bot en el modal submit se quedará un mensaje de "pensando" infinitamente en ephemeral, eso podría ponerse como en los Slash que despues de un tiempo da interacción fallida o algo ![Screenshot_2022-02-17-15-41-48-130_com.discord.jpg](https://user-images.githubusercontent.com/99443080/154505399-859068a3-b6b1-4ac4-90af-233cea9eb725.jpg)

**Comment by Mateo-tem** [comment]
**Puede parecer que está cargando infinitamente, pero no es así.**

Según la documentación de Discord API, sabemos que una Interacción (si es que no hay respuesta) tiene una duración de **15 minutos**. Tarde o temprano dirá Interacción Fallida.
