### ISSUE TITLE
DiscordAPIError: Interaction has already been acknowledged.

### ISSUE THREAD

**Issue by kinoshisocial** [Mateo-tem/discord-modals#68]
![image](https://user-images.githubusercontent.com/73155590/163240384-ba732e20-f705-47e0-99a7-9f29dceda35b.png)
![image](https://user-images.githubusercontent.com/73155590/163240493-c444b890-79e2-480f-82af-a6e4a0e0dd6d.png)

how to fix this error

**Comment by PabloRNC** [comment]
You have a reply to the interaction or a deferReply method on your command?

**Comment by kinoshisocial** [comment]
> You have a reply to the interaction or a deferReply method on your command?

what is deferReply, what should I do

**Comment by PabloRNC** [comment]
If u have <interaction>.deferReply()

**Comment by kinoshisocial** [comment]
> If u have .deferReply()

yes there is

**Comment by PabloRNC** [comment]
Remove that

**Comment by PabloRNC** [comment]
Thats the error

**Comment by kinoshisocial** [comment]
> Remove that

error

**Comment by PabloRNC** [comment]
Which?

**Comment by kinoshisocial** [comment]
> Which?

![image](https://user-images.githubusercontent.com/73155590/163283900-a4de8354-bb0f-4065-8d8c-095337a9d382.png)

**Comment by PabloRNC** [comment]
You reply the interaction or defer it you cannot reply the interaction or defer it cause It is a modal

**Comment by kinoshisocial** [comment]
> You reply the interaction or defer it you cannot reply the interaction or defer it cause It is a modal

What is the solution for the error?

**Comment by PabloRNC** [comment]
Can u pass to me all the command

**Comment by kinoshisocial** [comment]
> Can u pass to me all the command

of course add me on discord Kinoshi#0017

**Comment by PabloRNC** [comment]
Can u pass through GitHub please

**Comment by kinoshisocial** [comment]
> Can u pass through GitHub please

it happens too

**Comment by PabloRNC** [comment]
Cause if anyone has the error they can look here

**Comment by PabloRNC** [comment]
I mean you pass all the Code of the command

**Comment by kinoshisocial** [comment]
> Cause if anyone has the error they can look here

yes you are right

**Comment by PabloRNC** [comment]
I need you to send all the Code please to look what is wrong so you can send all the command Code please?

**Comment by kinoshisocial** [comment]
> I need you to send all the Code please to look what is wrong so you can send all the command Code please?

I put everything on my github

**Comment by kinoshisocial** [comment]
events/interactionCreate.js
SlashCommands/task/task.js

commands that give error when i edit

**Comment by PabloRNC** [comment]
A ok

**Comment by PabloRNC** [comment]
The thing i mean is to upload on this issue

**Comment by kinoshisocial** [comment]
> The thing i mean is to upload on this issue

I forgot 😅

**Comment by PabloRNC** [comment]
You can upload now please i did not find the command on your repos

**Comment by kinoshisocial** [comment]
> You can upload now please i did not find the command on your repos

I uploaded it again, this time there is the old interactionCreate file, including deferReply

https://github.com/kinoshisocial/error

**Comment by PabloRNC** [comment]
You have to remodel the interactionCreate so there is not a deferReply or that the modal file ignores this deferReply method

**Comment by kinoshisocial** [comment]
> You have to remodel the interactionCreate so there is not a deferReply or that the modal file ignores this deferReply method

When I remove deferReply, the commands give an error I don't know what to do

**Comment by PabloRNC** [comment]
You cannot do a editReply without a deferReply so instead of editReply put reply

**Comment by kinoshisocial** [comment]
> You cannot do a editReply without a deferReply so instead of editReply put reply

how, i never used v13

**Comment by PabloRNC** [comment]
Instead of interaction.followUp put interaction.reply

**Comment by kinoshisocial** [comment]
> Instead of interaction.followUp put interaction.reply

hmm

**Comment by PabloRNC** [comment]
And on your commands you Will have followUp or editReply change that to reply

**Comment by kinoshisocial** [comment]
> And on your commands you Will have followUp or editReply change that to reply

it worked thank you

**Comment by PabloRNC** [comment]
Glad to hear that
