### ISSUE TITLE
Add a FAQ in the readme

### ISSUE THREAD

**Issue by PabloRNC** [Mateo-tem/discord-modals#69]
It will be good to add a FAQ (frequent asked questions) apart on the readme because a lot of users have the same issues like "Interaction aknowledge", "Event modalSubmit on the command", "The client is not valid on this context", "The interaction is replied or defered". This will be fine because almost the half of the issues are that and It Will help the users reaching an answer faster than open an issue.

**Comment by Mateo-tem** [comment]
I will work on this. Thanks ;)

**Comment by Mateo-tem** [comment]
Added!

**Comment by PabloRNC** [comment]
😎
