### ISSUE TITLE
modal.interaction

### ISSUE THREAD

**Issue by PabloRNC** [Mateo-tem/discord-modals#7]
No sé si esto es un error o no está añadido o si no se puede añadir pero hay alguna forma de sacar los datos de la interaction de los modals? Hago un console log de modal.interaction y me da undefined no sé si eso no está añadido pero si es así puedes añadirlo si se puede?

**Comment by Mateo-tem** [comment]
**De hecho, el parámetro `modal` del evento `modalSubmit` es una interacción.**
Si haces un `console.log(modal)` te darás cuenta de lo que sale. Pertenece a la clase `ModalSubmitInteraction` que es una interacción como tal.
Espero te sirva.
