### ISSUE TITLE
How to use modals on button clicks?

### ISSUE THREAD

**Issue by AshuGuptaGamer** [Mateo-tem/discord-modals#70]
How do I use modals on button clicks? I tried giving it the interaction but it just throws errors.

**Comment by Mateo-tem** [comment]
What do you mean?

**Comment by AshuGuptaGamer** [comment]
I mean how do I send modals when someone clicks a button.

**Comment by Mateo-tem** [comment]
Oh, right. Can you show me the error?

**Comment by AshuGuptaGamer** [comment]
Error: Interaction has already been acknowledged.

**Comment by Mateo-tem** [comment]
You probably have `interaction#deferUpdate()`?

**Comment by AshuGuptaGamer** [comment]
Ohh yeah that was the issue. Thank you soo much

**Comment by Mateo-tem** [comment]
No problem ;)

**Comment by PabloRNC** [comment]
Because if that a faq its good
