### ISSUE TITLE
`.setValue is not a function`

### ISSUE THREAD

**Issue by rens-o** [Mateo-tem/discord-modals#71]
`.setValue is not a function`
Issue resolves when removing
![image](https://user-images.githubusercontent.com/91758660/163683786-db5f999a-0375-48ad-b812-a6be61eff70c.png)
 this line (.setValue("value")), but you can't retrieve the data anymore.

**Comment by Mateo-tem** [comment]
Is `.setDefaultValue()`, not `.setValue()`.
