### ISSUE TITLE
How can i post the modal in the specific channel and close the modal ?

### ISSUE THREAD

**Issue by Zarow-01** [Mateo-tem/discord-modals#72]
Hi! I want to post my modal in a special channel. Currently I'm doing this: `modal.guild.channels.cache.get(config.modal).send({ embeds: [embed] })` but, my modal won't close and write "an error occurred . Try again." except that the modal sends well in my channel. Would you help me?

**Comment by PabloRNC** [comment]
Can u send your Code?

**Comment by Developpement-Industry** [comment]
> Can u send your Code?

`client.on('modalSubmit', (modal) => {
    if(modal.customId === 'modal-Discord'){
    const firstResponse = modal.getTextInputValue('Text')
    const embed = new Discord.MessageEmbed()
    .setAuthor({ name: `${modal.user.tag} ➜ ${modal.user.id}`, iconURL: modal.user.displayAvatarURL({ dynamic: true }) })
    .setDescription(`\`\`\`\n${firstResponse}\n\`\`\``)
    .setImage('https://cdn.discordapp.com/attachments/943240010285592636/943476668662685697/Suggestion.png')
    .setColor("#ff7a00")
    .setTimestamp()
    modal.guild.channels.cache.get(config.modal).send({ embeds: [embed] })
    }
})`

**Comment by Developpement-Industry** [comment]
> What error do you have on console? Maybe it's because you don't have anything that "closes" the modal like modal.reply() / modal.followUp()...

![Capture](https://user-images.githubusercontent.com/102884028/164206098-e0b33c39-c869-4eeb-8437-5dd7b9ea76ac.png)
Heuuu, I never got this error

**Comment by PabloRNC** [comment]
The modal title has to be 45 or fewer

**Comment by Developpement-Industry** [comment]
> The modal title has to be 45 or fewer

It's not my code !

**Comment by PabloRNC** [comment]
But you send this error xd

**Comment by Zarow-01** [comment]
No :/

Le mer. 4 mai 2022 à 15:35, X_Comatose_X ***@***.***> a
écrit :

**Comment by Mateo-tem** [comment]
A modal can't be closed with a bot. The bot should reply in order to close it, or the user needs to click on the "Cancel" button.
