### ISSUE TITLE
[Collector Interaction] Interaction has already been acknowledged.

### ISSUE THREAD

**Issue by IxAlpha** [Mateo-tem/discord-modals#73]
So I've tried to use the collector interaction like:
```js
const msg = await interaction.followUp({ components: [row5], content: `Weird button just showed up!`, ephemeral: false })
const collector = msg.createMessageComponentCollector({ time: 90000 })

collector.on('collect', async (i) => {
    if(i.customId === 'trywordbtn') {
        showModal(modal, {
            client: client,
            interaction: i
        }) 
     }
})
```
The first time the command works fine, but the second time I use the command I get Discord API error with "interaction has been already acknowledged. Here's the modalSubmit event:
```js
 client.on('modalSubmit', async (modal) => {
            if(modal.customId === 'wordleinput') {
                await modal.deferReply({ ephemeral: true }) // Error from here belongs...
                const firstResponse = modal.getTextInputValue('wordinput')

                if(firstResponse === randomWordg) {
                    await modal.followUp({ content: `Congrats 🥳 You guessed the word right, and it was \`${randomWordg}\``, ephemeral: true })
                    
                    await interaction.editReply({ content: `Good job! \`⍟Soon\` tokens has been added to your wallet.`, components: [deadraw] })

                } else if(trys === 4) {
                    await modal.followUp({ content: `You've 4 attempts to guess the word.`, ephemeral: true })

                    await interaction.editReply({ content: `Hmm... You should think more about it!`, components: [row5] })
                    trys = trys - 1

                } else if(trys === 3) {
                    await modal.followUp({ content: `\`3 of 4\` Attempts left.`, ephemeral: true })

                    await interaction.editReply({ content: `2 more attempts left, it's really easy!`, components: [row5] })

                } else if(trys === 2) {
                    await modal.followUp({ content: `\`2 of 4\` Attempts left.`, ephemeral: true })

                    await interaction.editReply({ content: `Really it's that much hard?!`, components: [row5] })
                } else if(trys === 1) {
                    await modal.followUp({ content: `\`1 of 4\` Attempts left.`, ephemeral: true })

                    await interaction.editReply({ content: `Common, think think!`, components: [row5] })
                } 
                
                if(trys === 0) {
                    await modal.followUp({ content: `Game end! You lost...`, ephemeral: true })

                    await interaction.editReply({ content: `You've ran out of attempts.. the word was \`${randomWordg}\``, components: [deadraw] })
                }
            }  
});
```
I am suffering this issue ages ago, idk what to do to solve it.. any solution??

**Comment by Luncaaa** [comment]
Do you have the **client.on('modalSubmit)** method in the same file as the command? If so, what worked for me was moving that method to another file like main.js or with an event handler.

**Comment by Deffex0** [comment]
> Do you have the **client.on('modalSubmit)** method in the same file as the command? If so, what worked for me was moving that method to another file like main.js or with an event handler.

Well, I've tried to do that so I wanted to use the interaction from the command, so I've tried to use parameters, but the same issue still appears, here's example, in the component collector:
```js
const modalHandler = require('../../events/modalSubmit')

collector.on('collect', async (i) => {
    if(i.customId === 'button') {
        showModal({
             client: client,
             interaction: i
         })
        modalHandler(interaction, collector)
    }
})
```
And the event file
```js
const modalHandler = async (interaction, collector) => {
    client.on('modalSubmit', async (modal) => {
          // Th same event code goes here
    }
}

module.exports = modalHandler
```

**Comment by PabloRNC** [comment]
Do you have on the interactionCreate event a deferReply method?

**Comment by Deffex0** [comment]
> Do you have on the interactionCreate event a deferReply method?

Well, I use command handler, I've used the `interaction.deferReply()` first and then I've used `followUp` to reply with the rows..

Like:
```js
// On the top of the code
await interaction.deferReply()

// Some rows defining goes here...

// And now followUp with the components
const msg = await interaction.followUp({ ... })
```

**Comment by PabloRNC** [comment]
Delete the deferReply method and if u have followUp or editReply methods on your commands change It by reply or limit this deferReply method to all your command except this one

**Comment by Deffex0** [comment]
But it's not caused from the command interaction.. I've marked from where does the error belongs to, when I use `modal.deferReply()` for the second time, it errors

**Comment by PabloRNC** [comment]
The problem is the thing that i said to you

**Comment by PabloRNC** [comment]
Because the collector collect those interactions and you on your interactionCreate you deferReply that interaction and the error is because you cannot deferReply this interaction and use on the show Modal method

**Comment by PabloRNC** [comment]
Try It and you Will se

**Comment by PabloRNC** [comment]
You can do this instead of replace the followUp and editReply methods

```js

if(!<cmd> === "your_modal_command"){
interaction.deferReply()
}
```

**Comment by Deffex0** [comment]
Alrighty, should I disable the `interaction.deferReply()` from the command? And use `interaction.reply()` instead?

**Comment by PabloRNC** [comment]
If you do not understand something let me now

**Comment by Deffex0** [comment]
Perhaps meeting me on Discord? If so click this icon <a href="https://discord.com/users/361953717945368593"><img src="https://logodownload.org/wp-content/uploads/2017/11/discord-logo-2-1.png" height="14"></a> to get directed to my profile!

**Comment by Deffex0** [comment]
Yeah true, anyways, I've tried to not to use `Interaction#deferReply` and use `Interaction#reply` like:
```js
const msg = await interaction.reply({ components: [row5], content: `Weird buttons just showed up!`, ephemeral: false, fetchReply: true })
const collector = msg.createMessageComponentCollector({ time: 120000 })
```
But like uh, am bored like literally I don't know what to do, would be my pleasure if you explain me it step by step...

**Comment by Deffex0** [comment]
ps: I use `Interaction#deferReply` in all of my commands not in the event itself

**Comment by PabloRNC** [comment]
Whats the name of your command?

**Comment by Deffex0** [comment]
wordle

**Comment by PabloRNC** [comment]
ok

```js

if(!<cmd> === "wordle"){
interaction.deferReply()
}```

Like that and only you try the command and luckily it will works propertly

**Comment by PabloRNC** [comment]
in cmd put how you define your command

**Comment by Deffex0** [comment]
okay I'll try

**Comment by Deffex0** [comment]
so it has different if deferReply in the event or in the command file?

**Comment by Deffex0** [comment]
Well nope, still facing the issue...

**Comment by AidanOfficial** [comment]
@PabloRNC I'm having this same error, with nothing but the modalSubmit event giving a deferReply

you can contact me at 10KAIDAN#0001 on discord

**Comment by PabloRNC** [comment]
Show me your command and your interactionCreate

**Comment by xOnlyFadi** [comment]
@PabloRNC is it possible to edit the current message without following it up because the bot im making is using it like a ban reason and then edit the message saying banned successfully?

**Comment by PabloRNC** [comment]
Mmm i do not know what do you mean if can provide some screenshots

**Comment by PabloRNC** [comment]
> @PabloRNC is it possible to edit the current message without following it up because the bot im making is using it like a ban reason and then edit the message saying banned successfully?

You can like modal.reply with fetchReply in true and then edit It like a interaction.reply method

**Comment by xOnlyFadi** [comment]
> > @PabloRNC is it possible to edit the current message without following it up because the bot im making is using it like a ban reason and then edit the message saying banned successfully?
> 
> You can like modal.reply with fetchReply in true and then edit It like a interaction.reply method

i already changed to discord.js v14 and it had the necessary things with the function `awaitModalSubmit` made it that i can edit current message without making it reply again

https://user-images.githubusercontent.com/63213308/166118685-80769e88-066d-41c9-9e70-9496f1682c16.mp4

**Comment by PabloRNC** [comment]
You can edit It with modal.interaction.message.edit on the discord -modals npm i think

**Comment by xOnlyFadi** [comment]
it tried I just got undefined

**Comment by Mateo-tem** [comment]
On discord-modals is `modal.update(...)`.
