### ISSUE TITLE
modalSubmit won't work on DMs

### ISSUE THREAD

**Issue by Luncaaa** [Mateo-tem/discord-modals#75]
Hey o/

If I execute a command in a DM and make it open a modal, the modal will show up correctly but if I have a modalSubmit method, it will give an error when submiting the modal: **DiscordAPIError: Cannot execute action on a DM channel**

Is this a Discord limitation or can it be fixed?
Thanks

**Comment by Mateo-tem** [comment]
**Thanks for reporting this issue!**

This is not a Discord API limitation. Actually, is not a discord-modals problem, the problem probably is because of your *intents*. This maybe rejects the request because you don't have enabled some intents that are related to DM Channels.

**Comment by Luncaaa** [comment]
It's weird because if I try with a slash command, the modal works perfectly but if I use it with a button interaction in a messageCreate event, it will happen what I said above.

**Comment by Luncaaa** [comment]
This is my client: **const client = new Client({ intents: ["DIRECT_MESSAGES", "DIRECT_MESSAGE_REACTIONS", "DIRECT_MESSAGE_TYPING"], partials: ["MESSAGE", "CHANNEL", "REACTION"]}); // 98303**

The number at the end was what I had in "intents" before. Doesn't work either way.

**Comment by Luncaaa** [comment]
Nevermind, my bad. It's an error from another section of the code, not of discord-modals. Sorry 😅

**Comment by Mateo-tem** [comment]
Oh ok don't worry haha
