### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YumiDon** [Mateo-tem/discord-modals#76]
Good afternoon mate, I'm facing an error using modal...
The error insists on not sending whatever description I left inside the modal. I left above the way I'm using it. I would love it if you could answer me.

Thank you!
Sorry if there are any spelling mistakes, I'm from Brazil

[imagem 1](https://media.discordapp.net/attachments/960594131850244116/966110249499099166/unknown.png)
[Imagem 2](https://media.discordapp.net/attachments/960594131850244116/966110430726611034/unknown.png?width=724&height=610)
[Imagem 3](https://media.discordapp.net/attachments/960594131850244116/966110633475047504/unknown.png)

**Comment by YumiDon** [comment]
Erro a cima...

**Comment by Luncaaa** [comment]
Can you please send error from console?

And from just seeing, looks like you are checking if the modal has the ID "don" while the modal you have has the ID **"dev"**

**Comment by YumiDon** [comment]
@Luncaaa There is no error in the console. But I've already done it to change the ID to "dev", I tested both. But the error remains the same, in the terminal nothing happens.

**Comment by PabloRNC** [comment]
Where you have the modalSubmit event?

**Comment by YumiDon** [comment]
In my folder events: src>events>modalSubmit.js

**Comment by Mateo-tem** [comment]
Probably you need to put:

```javascript
const discordModals = require('discord-modals');
discordModals(client);
```

In your main file, in order to receive the modalSubmit event.
