### ISSUE TITLE
No ephemerals upon modal submit

### ISSUE THREAD

**Issue by StephenL13** [Mateo-tem/discord-modals#78]
Greetings. Currently, I'm attempting to create modals for my server's verification gate system. However, I'm having technical problems whenever I want to notify the user privately once they submit the answers through the modal. Right now, I ran the interaction command at a private admin channel. Is there any further way to resolve this? Thank you.

Portion of code:
![image](https://user-images.githubusercontent.com/67349718/164597028-1b51fceb-c83c-4d39-ba47-9da5618beea1.png)

Slash command
![image](https://user-images.githubusercontent.com/67349718/164594895-ba4b591a-f198-4202-8d46-b7d038a774b6.png)

Screenshot:
![image](https://user-images.githubusercontent.com/67349718/164594750-1e9b1617-2454-4d42-a331-51fe77f033a7.png)

**Comment by Mateo-tem** [comment]
Modal Submit Interactions don't support a directly ephemeral reply.

**Comment by Mateo-tem** [comment]
Take the example from the readme:

```javascript
const { Formatters } = require('discord.js');

client.on('modalSubmit', async (modal) => {
  if(modal.customId === 'modal-customid'){
    const firstResponse = modal.getTextInputValue('textinput-customid')
    await modal.deferReply({ ephemeral: true })
    modal.followUp({ content: 'Congrats! Powered by discord-modals.' + Formatters.codeBlock('markdown', firstResponse), ephemeral: true })
  }  
});
```

**Comment by StephenL13** [comment]
Sorry for the late reply, but thanks for this. Will look forward somehow to fix this on my end.
