### ISSUE TITLE
How to update the interaction the modal was first triggered by?

### ISSUE THREAD

**Issue by GraysonCAdams** [Mateo-tem/discord-modals#83]
In the examples I see, you can only provide a new, fresh response to modal submissions, but I would like to update the first interaction which opened the modal to begin with.

**What I would like to accomplish...**

1. User runs slash command
2. Slash command returns ephemeral response with instructions + one button
3. User clicks button, modal opens
4. User submits modal
5. **Edit the ephemeral response from Step 2**

Whereas it seems like based off your examples, Step 5 would have to be: "Respond with new response, so now there's two ephemeral replies in a row"

Is this workflow natively supported or will I need to slap together some sort of custom callback collector?

**Comment by PabloRNC** [comment]
I think that modals have the property interaction this that returns Interaction this interaction have a message property you can do

```js
modal.interaction.message.edit()
```
If not try instead modal.message.edit

**Comment by GraysonCAdams** [comment]
> I think that modals have the property interaction this that returns Interaction this interaction have a message property you can do
> 
> ```js
> modal.interaction.message.edit()
> ```
> 
> If not try instead modal.message.edit

Unfortunately if the initial reply was ephemeral, it fails because it cannot reference an ephemeral message ID.

**Comment by GraysonCAdams** [comment]
Solution: You perform a `.update()` on the ModalSubmitInteraction, which does not update the modal, but the OG interaction.
