### ISSUE TITLE
`DiscordAPIError: Interaction has already been acknowledged.`

### ISSUE THREAD

**Issue by Flynx7** [Mateo-tem/discord-modals#88]
When I click the button a modal is displayed.
It successfully collects data, but only once.
The second time, I get this error.
I could try the second time from the same account or a different account.
It just doesn't work.
https://srcshare.io/?id=6278f9cb0a2e527ec6f60de3

**Comment by Flynx7** [comment]
@Mateo-tem it is a request to you to kindly help me.

**Comment by xOnlyFadi** [comment]
> @Mateo-tem it is a request to you to kindly help me.

try removing and see what happens
```js
modal.followUp({ content: 'Your prediction was locked.', ephemeral: true })
```
