### ISSUE TITLE
Problem showed in modal when submit modal

### ISSUE THREAD

**Issue by DanielBUBU** [Mateo-tem/discord-modals#9]
Got error when sending, but the codes are executing normally in background, no error log in console

In my code, if pressing add, will show a modal.
After user input, will add 30 songs into queue,  send a embed if playlist is too long ,connect to voice chat etc...
(I tried to add 898 songs in the "modalSubmit" event ,got same error
so I send a embed to handle this, still don't work)

The project:
https://github.com/DanielBUBU/PD_maid

/config.json needs"clientId","guildId","globalPrefix","token" if you want to run this project

The playlist I test:
https://www.youtube.com/watch?v=K6k63SJQquo&list=PLnLMh6e929yc2qtV_qVYvX6_3Zg3251GV&index=2

![image](https://user-images.githubusercontent.com/54381631/154800563-4fce23a5-2d70-4246-947d-4d44090b9ddc.png)

![image](https://user-images.githubusercontent.com/54381631/154800454-f16d3b27-cb0a-4b6f-a59e-0a79d2bf291c.png)

**Comment by Mateo-tem** [comment]
I think it's missing modal.reply(). If there is not reply for the interaction (Modal Submit Interaction), an error will be showed in modal.

**Comment by DanielBUBU** [comment]
> I think it's missing modal.reply(). If there is not reply for the interaction (Modal Submit Interaction), an error will be showed in modal.

Yeah that works
THX for replying
