### ISSUE TITLE
modalSubmit don't work

### ISSUE THREAD

**Issue by ArsamDev** [Mateo-tem/discord-modals#96]

**Comment by PabloRNC** [comment]
Send error

**Comment by ArsamDev** [comment]
No Error but it not do anything when somebody submit a Modal

**Comment by PabloRNC** [comment]
Send Code

**Comment by PabloRNC** [comment]
Where you have the event?

**Comment by idk-pixel** [comment]
> Where you have the event?

index.js

**Comment by PabloRNC** [comment]
Mmm and the modal is shown?

**Comment by idk-pixel** [comment]
> Mmm and the modal is shown?

yes.

**Comment by idk-pixel** [comment]
> > Mmm and the modal is shown?
> 
> yes.

https://prod.liveshare.vsengsaas.visualstudio.com/join?96E5642DCCEAB9520B88718E924B6705CCF5 pls join this

**Comment by ArsamDev** [comment]
> is

Hey, have you Discord?

**Comment by idk-pixel** [comment]
> > is
> 
> Hey, have you Discord?

yeah its WhoAboutYT#5719

**Comment by ArsamDev** [comment]
> 

Okey, i'm in the Liveshare

**Comment by ArsamDev** [comment]
but i don't use Module.exports, i put all in the same File

**Comment by ArsamDev** [comment]
I have fixed it, you must init Modal
**discordModals(client); // Init the event;**

**Comment by ArsamDev** [comment]
> I have fixed it, you must init Modal **discordModals(client); // Init the event;**

*idk-pixel fixed it
